import type { LevelConfig } from "./types";

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    chapter: "sequence",
    title: "Le premier pas",
    mission: "La poule est juste devant. Appelle avancer() autant de fois qu'il y a de cases à parcourir.",
    hint: "Compte les cases vides entre le renard et la poule : il en faut deux.",
    map: ["F.C"],
    startDir: "E",
    commands: ["avancer"],
    concepts: ["Appel de fonction", "Séquence"],
    starter: "avancer()\n",
    bestLines: 2,
  },
  {
    id: 2,
    chapter: "sequence",
    title: "Le virage",
    mission: "La poule est au coin. Avance, puis tourne, puis avance encore.",
    hint: "Après deux pas vers l'est, tourne à gauche pour monter.",
    map: [
      "..C",
      ".#.",
      "F..",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite"],
    concepts: ["Séquence", "Changer de direction"],
    starter: "avancer()\n",
    bestLines: 5,
  },
  {
    id: 3,
    chapter: "sequence",
    title: "Autour du rocher",
    mission: "Un rocher barre la route. Contourne-le en enchaînant avances et virages.",
    hint: "Passe par le haut ou par le bas : avance, tourne, avance, re-tourne.",
    map: [
      ".....",
      "F.#.C",
      ".....",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite"],
    concepts: ["Séquence"],
    starter: "avancer()\n",
    bestLines: 9,
  },
  {
    id: 4,
    chapter: "sequence",
    title: "Le sentier en L",
    mission: "Suis le chemin jusqu'à la poule, instruction après instruction.",
    hint: "Visualise chaque case. N'écris que ce que le renard doit faire, dans l'ordre.",
    map: [
      "F....",
      "####.",
      "....C",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite"],
    concepts: ["Séquence"],
    starter: "avancer()\n",
    bestLines: 7,
  },
  {
    id: 5,
    chapter: "variables",
    title: "Le panneau",
    mission: "Le nombre d'étapes change à chaque essai. Lis-le, range-le dans une variable, puis avance de ce nombre.",
    hint: "pas = lire_nombre() puis avancer_de(pas). Ne code pas un nombre en dur.",
    map: ["FS......."],
    startDir: "E",
    commands: ["avancer", "avancer_de", "lire_nombre"],
    concepts: ["Variable", "Fonction avec retour"],
    starter: "pas = lire_nombre()\n",
    bestLines: 2,
    randomDistance: true,
  },
  {
    id: 6,
    chapter: "variables",
    title: "Le couloir mesuré",
    mission: "Le panneau indique la longueur du premier couloir. Lis-le, avance de cette distance, puis tourne et rejoins la poule.",
    hint: "Après avancer_de(pas), tourne à droite puis avance une fois.",
    map: [
      "FS...",
      "###C.",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite", "avancer_de", "lire_nombre"],
    concepts: ["Variable", "Séquence"],
    starter: "pas = lire_nombre()\n",
    bestLines: 5,
    fixedNumber: 3,
  },
  {
    id: 7,
    chapter: "conditions",
    title: "Gauche ou droite ?",
    mission: "Le panneau indique le côté où se trouve la poule. Il change à chaque essai : il faut un if / else.",
    hint: 'sens = lire_panneau() puis if sens == "gauche": ... else: ...',
    map: [
      "G.S.D",
      "..F..",
    ],
    startDir: "N",
    commands: ["avancer", "tourner_gauche", "tourner_droite", "lire_panneau"],
    concepts: ["Condition", "Chaîne de caractères"],
    starter: 'sens = lire_panneau()\n',
    bestLines: 7,
    randomSign: true,
  },
  {
    id: 8,
    chapter: "conditions",
    title: "Le carrefour",
    mission: "Lis le panneau, choisis le bon virage, puis avance jusqu'à la poule.",
    hint: "Le panneau se lit avant de tourner. Un seul des deux chemins mène à la poule.",
    map: [
      "G...D",
      ".###.",
      "..S..",
      "..F..",
    ],
    startDir: "N",
    commands: ["avancer", "tourner_gauche", "tourner_droite", "lire_panneau"],
    concepts: ["if / else"],
    starter: 'sens = lire_panneau()\n',
    bestLines: 8,
    randomSign: true,
  },
  {
    id: 9,
    chapter: "for",
    title: "La longue route",
    mission: "Trop de pas pour tout écrire à la main. Utilise une boucle for.",
    hint: "for _ in range(7): puis avancer() indenté.",
    map: ["F......C"],
    startDir: "E",
    commands: ["avancer"],
    concepts: ["Boucle bornée"],
    starter: "for _ in range(7):\n    avancer()\n",
    maxLines: 3,
    bestLines: 2,
  },
  {
    id: 10,
    chapter: "for",
    title: "Deux allées",
    mission: "Deux couloirs identiques séparés par un virage. Une boucle, un tour, une boucle.",
    hint: "for _ in range(3): avancer()  puis tourner_droite()  puis encore une boucle.",
    map: [
      "F...",
      "###.",
      "...C",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite"],
    concepts: ["Boucle", "Motif répétitif"],
    starter: "for _ in range(3):\n    avancer()\n",
    maxLines: 6,
    bestLines: 5,
  },
  {
    id: 11,
    chapter: "for",
    title: "Les marches",
    mission: "Chaque marche est le même petit parcours. Une boucle suffit.",
    hint: "Motif d'une marche : tourner à gauche, avancer, tourner à droite, avancer.",
    map: [
      "###.C",
      "##..#",
      "#..##",
      "..###",
      "F####",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite"],
    concepts: ["Boucle", "Motif"],
    starter: "for _ in range(4):\n    ",
    maxLines: 7,
    bestLines: 5,
  },
  {
    id: 12,
    chapter: "while",
    title: "Jusqu'au mur",
    mission: "La distance change. Avance tant qu'il n'y a pas de mur devant toi.",
    hint: "while not mur_devant(): avancer()",
    map: ["F........"],
    startDir: "E",
    commands: ["avancer", "mur_devant"],
    concepts: ["while", "Capteur"],
    starter: "while not mur_devant():\n    avancer()\n",
    maxLines: 3,
    bestLines: 2,
    randomDistance: true,
  },
  {
    id: 13,
    chapter: "while",
    title: "Cherche la poule",
    mission: "Avance tant que tu n'es pas sur la poule. Sa position change.",
    hint: "while not poule_atteinte(): avancer()",
    map: ["F........"],
    startDir: "E",
    commands: ["avancer", "poule_atteinte"],
    concepts: ["while", "Capteur"],
    starter: "while not poule_atteinte():\n    avancer()\n",
    maxLines: 3,
    bestLines: 2,
    randomDistance: true,
  },
  {
    id: 14,
    chapter: "while",
    title: "Le coude",
    mission: "Avance jusqu'au mur, tourne, puis continue jusqu'à la poule.",
    hint: "Deux boucles while, séparées par un tourner_droite().",
    map: [
      "F...#",
      "...C.",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite", "mur_devant", "poule_atteinte"],
    concepts: ["while", "Séquence de boucles"],
    starter: "while not mur_devant():\n    avancer()\n",
    bestLines: 6,
  },
  {
    id: 15,
    chapter: "while",
    title: "Le labyrinthe",
    mission: "Règle simple : si un mur est devant, tourne à droite, sinon avance. Continue jusqu'à la poule.",
    hint: "while not poule_atteinte(): if mur_devant(): tourner_droite() else: avancer()",
    map: [
      "F..",
      ".#.",
      ".C.",
    ],
    startDir: "E",
    commands: ["avancer", "tourner_gauche", "tourner_droite", "mur_devant", "poule_atteinte"],
    concepts: ["while", "if", "Capteurs"],
    starter: "while not poule_atteinte():\n    ",
    bestLines: 6,
  },
];

export function getLevel(id: number): LevelConfig {
  return LEVELS.find((level) => level.id === id) ?? LEVELS[0];
}
