# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hMH1YGzTSR-zYVdxpcnHti-i8nyPfXa
"""

for i in range(a): ; while condition : ; for elt in sequence : ;
fonction:
def nom_fonction(p1:type,...)->type:
  (return ...)

listes :
liste_1 = []
liste_2 = [1,2,3]
liste_3 = [[1,2,3],[4,5,6]]
 - Accéder à 1 elt :
liste_2 [1]
 - Rajouter 1 elt :
liste_2.append(4)
 - Supprimer 1 elt :
liste_2.pop(0)

Voiture : marque, modele, nb_portes, nb_ch, autonomie, couleur
class Voiture:
  def __ init__(marque:str,modele:str,...):
    self.Marque = marque
    self.Modele = modele

class Voiture :
  def __init__(self, marque:str, modele:str, nb_portes:int, nb_ch:int, autonomie:int, couleur:str):
    self.Marque = marque
    self.Modele = modele
    self.Nb_portes = nb_portes
    self.Nb_ch = nb_ch
    self.Autonomie = autonomie
    self.Couleur = couleur
    self.Allumee = False

  def allumer_voiture(self):
    if self.Allumee == False:
      self.Allumee = True
    else:
      print('Elle est déjà allumée')
  def __str__(self)->str:
    return self.Marque + " " + self.Modele + " " + str(self.Nb_ch)
a3 = Voiture("audi","a3",5,150,800,"noir")

a3.__str__()

"""Exemple :"""

import hashlib

texte = "Bonjour BTS SIO"
# 1. Encodage (String -> Bytes)
texte_bytes = texte.encode('utf-8')
# 2. Hachage
hash_object = hashlib.sha256(texte_bytes)
# 3. Conversion (Bytes -> Hex String)
empreinte = hash_object.hexdigest()

print(empreinte)
# Résultat : a2c4e... (64 caractères)

#Exercice 1.1 Premier Hash
import hashlib
import time
def test_hachage()->str:
  texte = input("Saisissez qql chose ! ")
  texte_bytes = texte.encode('utf-8')
  hash_object = hashlib.sha256(texte_bytes)
  empreinte = hash_object.hexdigest()

  Blockchain="Blockchain"
  blockchain="blockchain"

  print("Blockchain: " ,hashlib.sha256(Blockchain.encode('utf-8')).hexdigest())
  print("blockchain: ", hashlib.sha256(blockchain.encode('utf-8')).hexdigest())

  return empreinte

test_hachage()

"""3. Non les résulats sont complétements différents.

"""

class Block:
  def __init__(self, index:int, timestamp:str, data:str,
               previous_hash:str, hash:str):
    self.Index = index
    self.Timestamp = timestamp
    self.Data = data
    self.Previous_hash = previous_hash
    self.Hash = hash

  def calculate_hash(self):
    temp = self.Index + self.Timestamp + self.Data
    + self.Previous_hash + self.Hash
    return hashlib.sha256(temp.encode('utf-8')).hexdigest()

test = Block(2,'02/03/2026',"Alice doit 10€ à Bob","oieurgogikudfgdgdoigdiogdogfoi",)